#!/bin/bash
cd /var/www/vhosts/getshifter.io
if [ -e /var/www/vhosts/getshifter.io/composer.lock ]; then
  /usr/local/bin/composer update -n > /tmp/composer.log
else
  /usr/local/bin/composer install -n > /tmp/composer.log
fi
/usr/local/bin/composer install -n > /tmp/composer.log
cd app/themes/shifter
/usr/local/bin/npm install > /tmp/npm.log
/usr/local/bin/npm rebuild > /tmp/npm_rebuild.log
/usr/bin/gulp --production > /tmp/gulp.log
chown -R nginx:nginx /var/www/vhosts/getshifter.io
cd /var/www/vhosts/getshifter.io
/usr/local/bin/wp c3 flush all --allow-root > /tmp/flush_cdn.log
