#!/bin/bash
cd /var/www/vhosts/getshifter.io.sub
composer install > /tmp/composer.log
cd app/themes/shifter
npm install > /tmp/npm.log
gulp --production > /tmp/gulp.log
chown -R nginx:nginx /var/www/vhosts/getshifter.io.sub
